# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60157674f8df11fe78b2de8664db1b40c15770eec4e93238cb0293f683a5291556224335fabe9f32c8fe8bee217b8ab7144ac4a7821d478cc32ce192ce1c5171

test:
  secret_key_base: 61df9847961e632760c994941e40440ea07de2ea9cdfbe1a6960c8a37f713e5809f5894c16054184596df6f7468ada3be857d691e3bb4a3fc02317440b42d070

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
